version: "3"

vars:
  GOLANGCI_LINT_VERSION: v1.62.2

tasks:
  clean:
    cmd: go clean -r -cache -testcache -modcache

  tidy:
    cmd: go mod tidy -v -x

  clear-build-dir:
    cmds:
      - cmd: |-
          rm -rf ./bin
          mkdir -p ./bin/{client,server}
          cp ./config/client.ini ./bin/client/config.ini
          cp ./config/server.ini ./bin/server/config.ini

  build:client:
    env:
      CGO_ENABLED: 1
      CC: clang
      CXX: clang++
    cmds:
      - task: clear-build-dir
      - cmd: |-
          go build \
            -a \
            -buildvcs=true \
            -trimpath \
            -ldflags="-X 'main.Version={{default "dev" .VERSION}}' -compressdwarf=true -extldflags=-static -s -w -buildid=''" \
            -o ./bin/client/linkos.exe \
            ./cmd/client

  build:server:
    env:
      CC: clang
      CXX: clang++
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - task: clear-build-dir
      - cmd: |-
          go build \
            -a \
            -buildvcs=true \
            -trimpath \
            -tags='poll_opt gc_opt' \
            -ldflags="-X 'main.Version={{default "dev" .VERSION}}' -compressdwarf=true -extldflags=-static -s -w -buildid=''" \
            -o ./bin/server/linkos \
            ./cmd/server

  lint:
    internal: true
    requires:
      vars:
        - OUT_FORMAT
    cmd: |-
      go run \
        github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}} \
        run {{ if .FIX }}--fix {{ end }}\
        --print-resources-usage \
        --out-format="{{.OUT_FORMAT}}"

  lint:local:
    cmds:
      - task: lint
        vars:
          OUT_FORMAT: colored-line-number

  lint:local:fix:
    cmds:
      - task: lint
        vars:
          OUT_FORMAT: colored-line-number
          FIX: true

  lint:ci:
    cmds:
      - task: lint
        vars:
          OUT_FORMAT: colored-line-number
