version: "3"

vars:
  GOLANGCI_LINT_VERSION: v2.0.1

tasks:
  clean:
    cmd: go clean -r -cache -testcache -modcache

  tidy:
    cmd: go mod tidy -v -x

  clear-build-dir:client:
    cmds:
      - cmd: |-
          rm -rf ./bin/client
          mkdir -p ./bin/client
          cp ./config/client.ini ./bin/client/config.ini

  clear-build-dir:server:
    cmds:
      - cmd: |-
          rm -rf ./bin/server
          mkdir -p ./bin/server
          cp ./config/server.ini ./bin/server/config.ini

  build:client:
    env:
      CGO_ENABLED: 1
      CC: clang
      CXX: clang++
    cmds:
      - task: clear-build-dir:client
      - cmd: |-
          go build \
            -a \
            -trimpath \
            -ldflags="-X 'main.Version={{default "dev" .VERSION}}' -compressdwarf=true -extldflags=-static -s -w -buildid=''" \
            -o ./bin/client/linkos.exe \
            ./cmd/client

  build:server:
    env:
      CC: clang
      CXX: clang++
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - task: clear-build-dir:server
      - cmd: |-
          go build \
            -a \
            -trimpath \
            -tags='poll_opt gc_opt' \
            -ldflags="-X 'main.Version={{default "dev" .VERSION}}' -compressdwarf=true -extldflags=-static -s -w -buildid=''" \
            -o ./bin/server/linkos \
            ./cmd/server
  
  install-linter:
    status:
      - test -f ./tools/golangci-lint
    cmds:
      - curl -sSfL --tlsv1.3 https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b ./tools {{.GOLANGCI_LINT_VERSION}}

  lint:
    internal: true
    deps:
      - task: install-linter
    cmd: |-
      ./tools/golangci-lint \
        run {{ if .FIX }}--fix {{ end }}\
        --print-resources-usage \
        --output.text.path stdout

  lint:local:
    cmds:
      - task: lint

  lint:local:fix:
    cmds:
      - task: lint
        vars:
          FIX: true

  lint:ci:
    cmds:
      - task: lint
