name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
concurrency:
  group: ${{ github.workflow }}/${{ github.ref_type }}/${{ github.ref_name }}
  cancel-in-progress: true
permissions:
  contents: none
  deployments: none
  actions: none
  checks: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  lint-client:
    name: Lint Client
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
          check-latest: false
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: CLANG64
          location: D:\msys2
          update: true
          release: true
          install: base-devel mingw-w64-clang-x86_64-clang
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run Code Linter
        run: task lint:ci
  lint-server:
    name: Lint Server
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
          check-latest: false
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run Code Linter
        run: task lint:ci
  build-client:
    name: Build Client
    runs-on: windows-latest
    needs: lint-client
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
          check-latest: false
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: CLANG64
          location: D:\msys2
          update: true
          release: true
          install: base-devel mingw-w64-clang-x86_64-clang unzip mingw-w64-clang-x86_64-imagemagick
      - name: Get Clang Path
        id: clang
        run: |-
          echo "dir=${{ steps.msys2.outputs.msys2-location }}\clang64\bin" >> $env:GITHUB_OUTPUT
          ${{ steps.msys2.outputs.msys2-location }}\clang64\bin\clang --version
          ${{ steps.msys2.outputs.msys2-location }}\clang64\bin\clang++ --version
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Build
        env:
          CC: ${{ steps.clang.outputs.dir }}\clang
          CXX: ${{ steps.clang.outputs.dir }}\clang++
        run: task build:client
      - name: Update Manifest
        shell: msys2 {0}
        run: |-
          set -ex

          # From: https://tewarid.github.io/2020/09/03/create-a-windows-icon-file-using-imagemagick.html
          convert ./res/linkos.png -resize 16x16   -depth 32 ./res/16-32.png
          convert ./res/linkos.png -resize 32x32   -depth 32 ./res/32-32.png
          convert ./res/linkos.png -resize 48x48   -depth 32 ./res/48-32.png
          convert ./res/linkos.png -resize 256x256 -depth 32 ./res/256-32.png
          convert ./res/16-32.png ./res/32-32.png ./res/48-32.png ./res/256-32.png ./res/linkos.ico

          wget https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe -O rcedit.exe
          ./rcedit ./bin/client/linkos.exe --set-icon ./res/linkos.ico --set-requested-execution-level requireAdministrator
      - name: Compress Executable
        shell: msys2 {0}
        run: |
          set -ex
          VERSION=4.2.4
          workdir=$(pwd)
          temp_dir=$(mktemp -d)
          cd "$temp_dir"
          wget -q "https://github.com/upx/upx/releases/download/v${VERSION}/upx-${VERSION}-win64.zip"
          unzip "upx-${VERSION}-win64.zip"
          "./upx-${VERSION}-win64/upx.exe" --no-color --mono --no-progress --ultra-brute --no-backup "${workdir}/bin/client/linkos.exe"
          "./upx-${VERSION}-win64/upx.exe" --test "${workdir}/bin/client/linkos.exe"
          cd -
          rm -rfv "${temp_dir}"
      - name: ZIP Artifacts
        run: Compress-Archive -Path .\bin\client -DestinationPath client.zip
      - name: Get OS & Arch
        id: os_arch
        run: |-
          echo "os=$(go env GOOS)" >> $env:GITHUB_OUTPUT
          echo "arch=$(go env GOARCH)" >> $env:GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client_${{ steps.os_arch.outputs.os }}_${{ steps.os_arch.outputs.arch }}.zip
          path: ./client.zip
          compression-level: 0
          retention-days: 3
  build-server:
    name: Build Server
    runs-on: ubuntu-24.04
    needs: lint-server
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
          check-latest: false
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Build
        run: task build:server
      - name: Compress Executable
        run: |
          set -ex
          VERSION=4.2.4
          workdir=$(pwd)
          temp_dir=$(mktemp -d)
          cd "$temp_dir"
          wget -qO- "https://github.com/upx/upx/releases/download/v${VERSION}/upx-${VERSION}-amd64_linux.tar.xz" | tar -xJvf - "upx-${VERSION}-amd64_linux/upx"
          "./upx-${VERSION}-amd64_linux/upx" --no-color --mono --no-progress --ultra-brute --no-backup "${workdir}/bin/server/linkos"
          "./upx-${VERSION}-amd64_linux/upx" --test "${workdir}/bin/server/linkos"
          cd -
          rm -rfv "${temp_dir}"
      - name: Tar Artifacts
        run: tar -cvf server.tar ./bin/server/
      - name: Get OS & Arch
        id: os_arch
        run: |-
          echo "os=$(go env GOOS)" >> $GITHUB_OUTPUT
          echo "arch=$(go env GOARCH)" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server_${{ steps.os_arch.outputs.os }}_${{ steps.os_arch.outputs.arch }}.tar
          path: ./server.tar
          compression-level: 0
          retention-days: 3
